USE DATABASE MY_PROJECT;
USE SCHEMA SILVER;

-- 1. CRM Customer Info
CREATE OR REPLACE TABLE CRM_CUST_INFO (
    CST_ID             INT,
    CST_KEY            VARCHAR(50),
    CST_FIRSTNAME      VARCHAR(50),
    CST_LASTNAME       VARCHAR(50),
    CST_MARITAL_STATUS VARCHAR(50),
    CST_GNDR           VARCHAR(50),
    CST_CREATE_DATE    DATE,
    DWH_CREATE_DATE    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. CRM Product Info
CREATE OR REPLACE TABLE CRM_PRD_INFO (
    PRD_ID             INT,
    CAT_ID             VARCHAR(50),
    PRD_KEY            VARCHAR(50),
    PRD_NM             VARCHAR(50),
    PRD_COST           INT,
    PRD_LINE           VARCHAR(50),
    PRD_START_DT       DATE,
    PRD_END_DT         DATE,
    DWH_CREATE_DATE    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. CRM Sales Details
CREATE OR REPLACE TABLE CRM_SALES_DETAILS (
    SLS_ORD_NUM        VARCHAR(50),
    SLS_PRD_KEY        VARCHAR(50),
    SLS_CUST_ID        INT,
    SLS_ORDER_DT       DATE,
    SLS_SHIP_DT        DATE,
    SLS_DUE_DT         DATE,
    SLS_SALES          INT,
    SLS_QUANTITY       INT,
    SLS_PRICE          INT,
    DWH_CREATE_DATE    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. ERP Location
CREATE OR REPLACE TABLE ERP_LOC_A101 (
    CID                VARCHAR(50),
    CNTRY              VARCHAR(50),
    DWH_CREATE_DATE    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 5. ERP Customer
CREATE OR REPLACE TABLE ERP_CUST_AZ12 (
    CID                VARCHAR(50),
    BDATE              DATE,
    GEN                VARCHAR(50),
    DWH_CREATE_DATE    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 6. ERP Product Category
CREATE OR REPLACE TABLE ERP_PX_CAT_G1V2 (
    ID                 VARCHAR(50),
    CAT                VARCHAR(50),
    SUBCAT             VARCHAR(50),
    MAINTENANCE        VARCHAR(50),
    DWH_CREATE_DATE    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);